# Generated by Django 4.0.5 on 2022-06-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=50)),
                ('name_de', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git_hub', models.URLField()),
                ('linked_in', models.URLField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Denislav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me_en', models.TextField()),
                ('skills_first_en', models.TextField()),
                ('skills_second_en', models.TextField()),
                ('skills_third_en', models.TextField()),
                ('about_me_de', models.TextField()),
                ('skills_first_de', models.TextField()),
                ('skills_second_de', models.TextField()),
                ('skills_third_de', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_en', models.CharField(max_length=20)),
                ('level_en', models.CharField(max_length=20)),
                ('language_de', models.CharField(max_length=20)),
                ('level_de', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=50)),
                ('duration_en', models.CharField(max_length=50)),
                ('description_en', models.TextField()),
                ('used', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('demo', models.URLField(null=True)),
                ('source_code', models.URLField(null=True)),
                ('title_de', models.CharField(max_length=50)),
                ('duration_de', models.CharField(max_length=50)),
                ('description_de', models.TextField()),
            ],
        ),
    ]
