# Generated by Django 4.0.5 on 2022-06-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cv', '0004_denislav_first_name_denislav_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_en', models.CharField(max_length=200)),
                ('head_de', models.CharField(max_length=200)),
            ],
        ),
    ]
