# Generated by Django 4.0.5 on 2022-06-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cv', '0005_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='name_de',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='name_en',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='head',
            name='head_de',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='head',
            name='head_en',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='language',
            name='language_de',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='language',
            name='language_en',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='language',
            name='level_de',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='language',
            name='level_en',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='duration_de',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='project',
            name='duration_en',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='project',
            name='title_de',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='project',
            name='used',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='work',
            name='position_de',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='work',
            name='position_en',
            field=models.CharField(max_length=70),
        ),
    ]
