# Generated by Django 4.0.5 on 2022-06-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cv', '0002_denislav_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('position_en', models.CharField(max_length=50)),
                ('employer_en', models.CharField(max_length=50)),
                ('description_en', models.TextField()),
                ('position_de', models.CharField(max_length=50)),
                ('employer_de', models.CharField(max_length=50)),
                ('description_de', models.TextField()),
            ],
        ),
    ]
